spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hrmanagementsystem
    username: arzu
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
